// WARNING: This file has automatically been generated on Wed, 22 May 2024 01:06:30 KST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "rocm_smi/rocm_smi.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

