// WARNING: This file has automatically been generated on Wed, 22 May 2024 01:06:30 KST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Go Bindings for ROCm System Management Interface (ROCm SMI) Library
*/
package rsmi
