// WARNING: This file has automatically been generated on Wed, 22 May 2024 00:28:34 KST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package rsmi

/*
#cgo linux LDFLAGS: -Wl,--export-dynamic -Wl,--unresolved-symbols=ignore-in-object-files
#include "rocm_smi/rocm_smi.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

// rsmi_init function as declared in rocm_smi/rocm_smi.h:1199
func rsmi_init(init_flags uint64) rsmi_status {
	cinit_flags, cinit_flagsAllocMap := (C.uint64_t)(init_flags), cgoAllocsUnknown
	__ret := C.rsmi_init(cinit_flags)
	runtime.KeepAlive(cinit_flagsAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_shut_down function as declared in rocm_smi/rocm_smi.h:1206
func rsmi_shut_down() rsmi_status {
	__ret := C.rsmi_shut_down()
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_num_monitor_devices function as declared in rocm_smi/rocm_smi.h:1227
func rsmi_num_monitor_devices(num_devices *uint32) rsmi_status {
	cnum_devices, cnum_devicesAllocMap := (*C.uint32_t)(unsafe.Pointer(num_devices)), cgoAllocsUnknown
	__ret := C.rsmi_num_monitor_devices(cnum_devices)
	runtime.KeepAlive(cnum_devicesAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_id_get function as declared in rocm_smi/rocm_smi.h:1256
func rsmi_dev_id_get(dv_ind uint32, id *uint16) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cid, cidAllocMap := (*C.uint16_t)(unsafe.Pointer(id)), cgoAllocsUnknown
	__ret := C.rsmi_dev_id_get(cdv_ind, cid)
	runtime.KeepAlive(cidAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_revision_get function as declared in rocm_smi/rocm_smi.h:1272
func rsmi_dev_revision_get(dv_ind uint32, revision *uint16) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	crevision, crevisionAllocMap := (*C.uint16_t)(unsafe.Pointer(revision)), cgoAllocsUnknown
	__ret := C.rsmi_dev_revision_get(cdv_ind, crevision)
	runtime.KeepAlive(crevisionAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_sku_get function as declared in rocm_smi/rocm_smi.h:1298
func rsmi_dev_sku_get(dv_ind uint32, sku *uint16) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	csku, cskuAllocMap := (*C.uint16_t)(unsafe.Pointer(sku)), cgoAllocsUnknown
	__ret := C.rsmi_dev_sku_get(cdv_ind, csku)
	runtime.KeepAlive(cskuAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_vendor_id_get function as declared in rocm_smi/rocm_smi.h:1323
func rsmi_dev_vendor_id_get(dv_ind uint32, id *uint16) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cid, cidAllocMap := (*C.uint16_t)(unsafe.Pointer(id)), cgoAllocsUnknown
	__ret := C.rsmi_dev_vendor_id_get(cdv_ind, cid)
	runtime.KeepAlive(cidAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_name_get function as declared in rocm_smi/rocm_smi.h:1359
func rsmi_dev_name_get(dv_ind uint32, name *byte, len uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cname, cnameAllocMap := (*C.char)(unsafe.Pointer(name)), cgoAllocsUnknown
	clen, clenAllocMap := (C.size_t)(len), cgoAllocsUnknown
	__ret := C.rsmi_dev_name_get(cdv_ind, cname, clen)
	runtime.KeepAlive(clenAllocMap)
	runtime.KeepAlive(cnameAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_brand_get function as declared in rocm_smi/rocm_smi.h:1393
func rsmi_dev_brand_get(dv_ind uint32, brand *byte, len uint32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cbrand, cbrandAllocMap := (*C.char)(unsafe.Pointer(brand)), cgoAllocsUnknown
	clen, clenAllocMap := (C.uint32_t)(len), cgoAllocsUnknown
	__ret := C.rsmi_dev_brand_get(cdv_ind, cbrand, clen)
	runtime.KeepAlive(clenAllocMap)
	runtime.KeepAlive(cbrandAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_vendor_name_get function as declared in rocm_smi/rocm_smi.h:1429
func rsmi_dev_vendor_name_get(dv_ind uint32, name *byte, len uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cname, cnameAllocMap := (*C.char)(unsafe.Pointer(name)), cgoAllocsUnknown
	clen, clenAllocMap := (C.size_t)(len), cgoAllocsUnknown
	__ret := C.rsmi_dev_vendor_name_get(cdv_ind, cname, clen)
	runtime.KeepAlive(clenAllocMap)
	runtime.KeepAlive(cnameAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_vram_vendor_get function as declared in rocm_smi/rocm_smi.h:1454
func rsmi_dev_vram_vendor_get(dv_ind uint32, brand *byte, len uint32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cbrand, cbrandAllocMap := (*C.char)(unsafe.Pointer(brand)), cgoAllocsUnknown
	clen, clenAllocMap := (C.uint32_t)(len), cgoAllocsUnknown
	__ret := C.rsmi_dev_vram_vendor_get(cdv_ind, cbrand, clen)
	runtime.KeepAlive(clenAllocMap)
	runtime.KeepAlive(cbrandAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_serial_number_get function as declared in rocm_smi/rocm_smi.h:1485
func rsmi_dev_serial_number_get(dv_ind uint32, serial_num *byte, len uint32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cserial_num, cserial_numAllocMap := (*C.char)(unsafe.Pointer(serial_num)), cgoAllocsUnknown
	clen, clenAllocMap := (C.uint32_t)(len), cgoAllocsUnknown
	__ret := C.rsmi_dev_serial_number_get(cdv_ind, cserial_num, clen)
	runtime.KeepAlive(clenAllocMap)
	runtime.KeepAlive(cserial_numAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_subsystem_id_get function as declared in rocm_smi/rocm_smi.h:1510
func rsmi_dev_subsystem_id_get(dv_ind uint32, id *uint16) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cid, cidAllocMap := (*C.uint16_t)(unsafe.Pointer(id)), cgoAllocsUnknown
	__ret := C.rsmi_dev_subsystem_id_get(cdv_ind, cid)
	runtime.KeepAlive(cidAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_subsystem_name_get function as declared in rocm_smi/rocm_smi.h:1547
func rsmi_dev_subsystem_name_get(dv_ind uint32, name *byte, len uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cname, cnameAllocMap := (*C.char)(unsafe.Pointer(name)), cgoAllocsUnknown
	clen, clenAllocMap := (C.size_t)(len), cgoAllocsUnknown
	__ret := C.rsmi_dev_subsystem_name_get(cdv_ind, cname, clen)
	runtime.KeepAlive(clenAllocMap)
	runtime.KeepAlive(cnameAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_drm_render_minor_get function as declared in rocm_smi/rocm_smi.h:1567
func rsmi_dev_drm_render_minor_get(dv_ind uint32, minor *uint32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cminor, cminorAllocMap := (*C.uint32_t)(unsafe.Pointer(minor)), cgoAllocsUnknown
	__ret := C.rsmi_dev_drm_render_minor_get(cdv_ind, cminor)
	runtime.KeepAlive(cminorAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_subsystem_vendor_id_get function as declared in rocm_smi/rocm_smi.h:1591
func rsmi_dev_subsystem_vendor_id_get(dv_ind uint32, id *uint16) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cid, cidAllocMap := (*C.uint16_t)(unsafe.Pointer(id)), cgoAllocsUnknown
	__ret := C.rsmi_dev_subsystem_vendor_id_get(cdv_ind, cid)
	runtime.KeepAlive(cidAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_unique_id_get function as declared in rocm_smi/rocm_smi.h:1614
func rsmi_dev_unique_id_get(dv_ind uint32, id *uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cid, cidAllocMap := (*C.uint64_t)(unsafe.Pointer(id)), cgoAllocsUnknown
	__ret := C.rsmi_dev_unique_id_get(cdv_ind, cid)
	runtime.KeepAlive(cidAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_xgmi_physical_id_get function as declared in rocm_smi/rocm_smi.h:1630
func rsmi_dev_xgmi_physical_id_get(dv_ind uint32, id *uint16) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cid, cidAllocMap := (*C.uint16_t)(unsafe.Pointer(id)), cgoAllocsUnknown
	__ret := C.rsmi_dev_xgmi_physical_id_get(cdv_ind, cid)
	runtime.KeepAlive(cidAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_guid_get function as declared in rocm_smi/rocm_smi.h:1654
func rsmi_dev_guid_get(dv_ind uint32, guid *uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cguid, cguidAllocMap := (*C.uint64_t)(unsafe.Pointer(guid)), cgoAllocsUnknown
	__ret := C.rsmi_dev_guid_get(cdv_ind, cguid)
	runtime.KeepAlive(cguidAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_node_id_get function as declared in rocm_smi/rocm_smi.h:1678
func rsmi_dev_node_id_get(dv_ind uint32, node_id *uint32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cnode_id, cnode_idAllocMap := (*C.uint32_t)(unsafe.Pointer(node_id)), cgoAllocsUnknown
	__ret := C.rsmi_dev_node_id_get(cdv_ind, cnode_id)
	runtime.KeepAlive(cnode_idAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_pci_bandwidth_get function as declared in rocm_smi/rocm_smi.h:1708
func rsmi_dev_pci_bandwidth_get(dv_ind uint32, bandwidth *rsmi_pcie_bandwidth) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cbandwidth, cbandwidthAllocMap := bandwidth.PassRef()
	__ret := C.rsmi_dev_pci_bandwidth_get(cdv_ind, cbandwidth)
	runtime.KeepAlive(cbandwidthAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_pci_id_get function as declared in rocm_smi/rocm_smi.h:1747
func rsmi_dev_pci_id_get(dv_ind uint32, bdfid *uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cbdfid, cbdfidAllocMap := (*C.uint64_t)(unsafe.Pointer(bdfid)), cgoAllocsUnknown
	__ret := C.rsmi_dev_pci_id_get(cdv_ind, cbdfid)
	runtime.KeepAlive(cbdfidAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_topo_numa_affinity_get function as declared in rocm_smi/rocm_smi.h:1771
func rsmi_topo_numa_affinity_get(dv_ind uint32, numa_node *int32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cnuma_node, cnuma_nodeAllocMap := (*C.int32_t)(unsafe.Pointer(numa_node)), cgoAllocsUnknown
	__ret := C.rsmi_topo_numa_affinity_get(cdv_ind, cnuma_node)
	runtime.KeepAlive(cnuma_nodeAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_pci_throughput_get function as declared in rocm_smi/rocm_smi.h:1797
func rsmi_dev_pci_throughput_get(dv_ind uint32, sent *uint64, received *uint64, max_pkt_sz *uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	csent, csentAllocMap := (*C.uint64_t)(unsafe.Pointer(sent)), cgoAllocsUnknown
	creceived, creceivedAllocMap := (*C.uint64_t)(unsafe.Pointer(received)), cgoAllocsUnknown
	cmax_pkt_sz, cmax_pkt_szAllocMap := (*C.uint64_t)(unsafe.Pointer(max_pkt_sz)), cgoAllocsUnknown
	__ret := C.rsmi_dev_pci_throughput_get(cdv_ind, csent, creceived, cmax_pkt_sz)
	runtime.KeepAlive(cmax_pkt_szAllocMap)
	runtime.KeepAlive(creceivedAllocMap)
	runtime.KeepAlive(csentAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_pci_replay_counter_get function as declared in rocm_smi/rocm_smi.h:1822
func rsmi_dev_pci_replay_counter_get(dv_ind uint32, counter *uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	ccounter, ccounterAllocMap := (*C.uint64_t)(unsafe.Pointer(counter)), cgoAllocsUnknown
	__ret := C.rsmi_dev_pci_replay_counter_get(cdv_ind, ccounter)
	runtime.KeepAlive(ccounterAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_pci_bandwidth_set function as declared in rocm_smi/rocm_smi.h:1861
func rsmi_dev_pci_bandwidth_set(dv_ind uint32, bw_bitmask uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cbw_bitmask, cbw_bitmaskAllocMap := (C.uint64_t)(bw_bitmask), cgoAllocsUnknown
	__ret := C.rsmi_dev_pci_bandwidth_set(cdv_ind, cbw_bitmask)
	runtime.KeepAlive(cbw_bitmaskAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_power_ave_get function as declared in rocm_smi/rocm_smi.h:1901
func rsmi_dev_power_ave_get(dv_ind uint32, sensor_ind uint32, power *uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	csensor_ind, csensor_indAllocMap := (C.uint32_t)(sensor_ind), cgoAllocsUnknown
	cpower, cpowerAllocMap := (*C.uint64_t)(unsafe.Pointer(power)), cgoAllocsUnknown
	__ret := C.rsmi_dev_power_ave_get(cdv_ind, csensor_ind, cpower)
	runtime.KeepAlive(cpowerAllocMap)
	runtime.KeepAlive(csensor_indAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_current_socket_power_get function as declared in rocm_smi/rocm_smi.h:1925
func rsmi_dev_current_socket_power_get(dv_ind uint32, socket_power *uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	csocket_power, csocket_powerAllocMap := (*C.uint64_t)(unsafe.Pointer(socket_power)), cgoAllocsUnknown
	__ret := C.rsmi_dev_current_socket_power_get(cdv_ind, csocket_power)
	runtime.KeepAlive(csocket_powerAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_power_get function as declared in rocm_smi/rocm_smi.h:1961
func rsmi_dev_power_get(dv_ind uint32, power *uint64, _type *RSMI_POWER) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cpower, cpowerAllocMap := (*C.uint64_t)(unsafe.Pointer(power)), cgoAllocsUnknown
	c_type, c_typeAllocMap := (*C.RSMI_POWER_TYPE)(unsafe.Pointer(_type)), cgoAllocsUnknown
	__ret := C.rsmi_dev_power_get(cdv_ind, cpower, c_type)
	runtime.KeepAlive(c_typeAllocMap)
	runtime.KeepAlive(cpowerAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_energy_count_get function as declared in rocm_smi/rocm_smi.h:1995
func rsmi_dev_energy_count_get(dv_ind uint32, power *uint64, counter_resolution *float32, timestamp *uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cpower, cpowerAllocMap := (*C.uint64_t)(unsafe.Pointer(power)), cgoAllocsUnknown
	ccounter_resolution, ccounter_resolutionAllocMap := (*C.float)(unsafe.Pointer(counter_resolution)), cgoAllocsUnknown
	ctimestamp, ctimestampAllocMap := (*C.uint64_t)(unsafe.Pointer(timestamp)), cgoAllocsUnknown
	__ret := C.rsmi_dev_energy_count_get(cdv_ind, cpower, ccounter_resolution, ctimestamp)
	runtime.KeepAlive(ctimestampAllocMap)
	runtime.KeepAlive(ccounter_resolutionAllocMap)
	runtime.KeepAlive(cpowerAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_power_cap_get function as declared in rocm_smi/rocm_smi.h:2024
func rsmi_dev_power_cap_get(dv_ind uint32, sensor_ind uint32, cap *uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	csensor_ind, csensor_indAllocMap := (C.uint32_t)(sensor_ind), cgoAllocsUnknown
	ccap, ccapAllocMap := (*C.uint64_t)(unsafe.Pointer(cap)), cgoAllocsUnknown
	__ret := C.rsmi_dev_power_cap_get(cdv_ind, csensor_ind, ccap)
	runtime.KeepAlive(ccapAllocMap)
	runtime.KeepAlive(csensor_indAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_power_cap_default_get function as declared in rocm_smi/rocm_smi.h:2048
func rsmi_dev_power_cap_default_get(dv_ind uint32, default_cap *uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cdefault_cap, cdefault_capAllocMap := (*C.uint64_t)(unsafe.Pointer(default_cap)), cgoAllocsUnknown
	__ret := C.rsmi_dev_power_cap_default_get(cdv_ind, cdefault_cap)
	runtime.KeepAlive(cdefault_capAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_power_cap_range_get function as declared in rocm_smi/rocm_smi.h:2082
func rsmi_dev_power_cap_range_get(dv_ind uint32, sensor_ind uint32, max *uint64, min *uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	csensor_ind, csensor_indAllocMap := (C.uint32_t)(sensor_ind), cgoAllocsUnknown
	cmax, cmaxAllocMap := (*C.uint64_t)(unsafe.Pointer(max)), cgoAllocsUnknown
	cmin, cminAllocMap := (*C.uint64_t)(unsafe.Pointer(min)), cgoAllocsUnknown
	__ret := C.rsmi_dev_power_cap_range_get(cdv_ind, csensor_ind, cmax, cmin)
	runtime.KeepAlive(cminAllocMap)
	runtime.KeepAlive(cmaxAllocMap)
	runtime.KeepAlive(csensor_indAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_power_cap_set function as declared in rocm_smi/rocm_smi.h:2113
func rsmi_dev_power_cap_set(dv_ind uint32, sensor_ind uint32, cap uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	csensor_ind, csensor_indAllocMap := (C.uint32_t)(sensor_ind), cgoAllocsUnknown
	ccap, ccapAllocMap := (C.uint64_t)(cap), cgoAllocsUnknown
	__ret := C.rsmi_dev_power_cap_set(cdv_ind, csensor_ind, ccap)
	runtime.KeepAlive(ccapAllocMap)
	runtime.KeepAlive(csensor_indAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_power_profile_set function as declared in rocm_smi/rocm_smi.h:2135
func rsmi_dev_power_profile_set(dv_ind uint32, reserved uint32, profile rsmi_power_profile_preset_masks) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	creserved, creservedAllocMap := (C.uint32_t)(reserved), cgoAllocsUnknown
	cprofile, cprofileAllocMap := (C.rsmi_power_profile_preset_masks_t)(profile), cgoAllocsUnknown
	__ret := C.rsmi_dev_power_profile_set(cdv_ind, creserved, cprofile)
	runtime.KeepAlive(cprofileAllocMap)
	runtime.KeepAlive(creservedAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_memory_total_get function as declared in rocm_smi/rocm_smi.h:2174
func rsmi_dev_memory_total_get(dv_ind uint32, mem_type rsmi_memory_type, total *uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cmem_type, cmem_typeAllocMap := (C.rsmi_memory_type_t)(mem_type), cgoAllocsUnknown
	ctotal, ctotalAllocMap := (*C.uint64_t)(unsafe.Pointer(total)), cgoAllocsUnknown
	__ret := C.rsmi_dev_memory_total_get(cdv_ind, cmem_type, ctotal)
	runtime.KeepAlive(ctotalAllocMap)
	runtime.KeepAlive(cmem_typeAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_memory_usage_get function as declared in rocm_smi/rocm_smi.h:2204
func rsmi_dev_memory_usage_get(dv_ind uint32, mem_type rsmi_memory_type, used *uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cmem_type, cmem_typeAllocMap := (C.rsmi_memory_type_t)(mem_type), cgoAllocsUnknown
	cused, cusedAllocMap := (*C.uint64_t)(unsafe.Pointer(used)), cgoAllocsUnknown
	__ret := C.rsmi_dev_memory_usage_get(cdv_ind, cmem_type, cused)
	runtime.KeepAlive(cusedAllocMap)
	runtime.KeepAlive(cmem_typeAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_memory_busy_percent_get function as declared in rocm_smi/rocm_smi.h:2230
func rsmi_dev_memory_busy_percent_get(dv_ind uint32, busy_percent *uint32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cbusy_percent, cbusy_percentAllocMap := (*C.uint32_t)(unsafe.Pointer(busy_percent)), cgoAllocsUnknown
	__ret := C.rsmi_dev_memory_busy_percent_get(cdv_ind, cbusy_percent)
	runtime.KeepAlive(cbusy_percentAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_memory_reserved_pages_get function as declared in rocm_smi/rocm_smi.h:2268
func rsmi_dev_memory_reserved_pages_get(dv_ind uint32, num_pages *uint32, records *rsmi_retired_page_record) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cnum_pages, cnum_pagesAllocMap := (*C.uint32_t)(unsafe.Pointer(num_pages)), cgoAllocsUnknown
	crecords, crecordsAllocMap := records.PassRef()
	__ret := C.rsmi_dev_memory_reserved_pages_get(cdv_ind, cnum_pages, crecords)
	runtime.KeepAlive(crecordsAllocMap)
	runtime.KeepAlive(cnum_pagesAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_fan_rpms_get function as declared in rocm_smi/rocm_smi.h:2303
func rsmi_dev_fan_rpms_get(dv_ind uint32, sensor_ind uint32, speed *int64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	csensor_ind, csensor_indAllocMap := (C.uint32_t)(sensor_ind), cgoAllocsUnknown
	cspeed, cspeedAllocMap := (*C.int64_t)(unsafe.Pointer(speed)), cgoAllocsUnknown
	__ret := C.rsmi_dev_fan_rpms_get(cdv_ind, csensor_ind, cspeed)
	runtime.KeepAlive(cspeedAllocMap)
	runtime.KeepAlive(csensor_indAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_fan_speed_get function as declared in rocm_smi/rocm_smi.h:2333
func rsmi_dev_fan_speed_get(dv_ind uint32, sensor_ind uint32, speed *int64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	csensor_ind, csensor_indAllocMap := (C.uint32_t)(sensor_ind), cgoAllocsUnknown
	cspeed, cspeedAllocMap := (*C.int64_t)(unsafe.Pointer(speed)), cgoAllocsUnknown
	__ret := C.rsmi_dev_fan_speed_get(cdv_ind, csensor_ind, cspeed)
	runtime.KeepAlive(cspeedAllocMap)
	runtime.KeepAlive(csensor_indAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_fan_speed_max_get function as declared in rocm_smi/rocm_smi.h:2361
func rsmi_dev_fan_speed_max_get(dv_ind uint32, sensor_ind uint32, max_speed *uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	csensor_ind, csensor_indAllocMap := (C.uint32_t)(sensor_ind), cgoAllocsUnknown
	cmax_speed, cmax_speedAllocMap := (*C.uint64_t)(unsafe.Pointer(max_speed)), cgoAllocsUnknown
	__ret := C.rsmi_dev_fan_speed_max_get(cdv_ind, csensor_ind, cmax_speed)
	runtime.KeepAlive(cmax_speedAllocMap)
	runtime.KeepAlive(csensor_indAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_temp_metric_get function as declared in rocm_smi/rocm_smi.h:2394
func rsmi_dev_temp_metric_get(dv_ind uint32, sensor_type uint32, metric rsmi_temperature_metric, temperature *int64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	csensor_type, csensor_typeAllocMap := (C.uint32_t)(sensor_type), cgoAllocsUnknown
	cmetric, cmetricAllocMap := (C.rsmi_temperature_metric_t)(metric), cgoAllocsUnknown
	ctemperature, ctemperatureAllocMap := (*C.int64_t)(unsafe.Pointer(temperature)), cgoAllocsUnknown
	__ret := C.rsmi_dev_temp_metric_get(cdv_ind, csensor_type, cmetric, ctemperature)
	runtime.KeepAlive(ctemperatureAllocMap)
	runtime.KeepAlive(cmetricAllocMap)
	runtime.KeepAlive(csensor_typeAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_volt_metric_get function as declared in rocm_smi/rocm_smi.h:2427
func rsmi_dev_volt_metric_get(dv_ind uint32, sensor_type rsmi_voltage_type, metric rsmi_voltage_metric, voltage *int64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	csensor_type, csensor_typeAllocMap := (C.rsmi_voltage_type_t)(sensor_type), cgoAllocsUnknown
	cmetric, cmetricAllocMap := (C.rsmi_voltage_metric_t)(metric), cgoAllocsUnknown
	cvoltage, cvoltageAllocMap := (*C.int64_t)(unsafe.Pointer(voltage)), cgoAllocsUnknown
	__ret := C.rsmi_dev_volt_metric_get(cdv_ind, csensor_type, cmetric, cvoltage)
	runtime.KeepAlive(cvoltageAllocMap)
	runtime.KeepAlive(cmetricAllocMap)
	runtime.KeepAlive(csensor_typeAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_fan_reset function as declared in rocm_smi/rocm_smi.h:2452
func rsmi_dev_fan_reset(dv_ind uint32, sensor_ind uint32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	csensor_ind, csensor_indAllocMap := (C.uint32_t)(sensor_ind), cgoAllocsUnknown
	__ret := C.rsmi_dev_fan_reset(cdv_ind, csensor_ind)
	runtime.KeepAlive(csensor_indAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_fan_speed_set function as declared in rocm_smi/rocm_smi.h:2476
func rsmi_dev_fan_speed_set(dv_ind uint32, sensor_ind uint32, speed uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	csensor_ind, csensor_indAllocMap := (C.uint32_t)(sensor_ind), cgoAllocsUnknown
	cspeed, cspeedAllocMap := (C.uint64_t)(speed), cgoAllocsUnknown
	__ret := C.rsmi_dev_fan_speed_set(cdv_ind, csensor_ind, cspeed)
	runtime.KeepAlive(cspeedAllocMap)
	runtime.KeepAlive(csensor_indAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_busy_percent_get function as declared in rocm_smi/rocm_smi.h:2511
func rsmi_dev_busy_percent_get(dv_ind uint32, busy_percent *uint32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cbusy_percent, cbusy_percentAllocMap := (*C.uint32_t)(unsafe.Pointer(busy_percent)), cgoAllocsUnknown
	__ret := C.rsmi_dev_busy_percent_get(cdv_ind, cbusy_percent)
	runtime.KeepAlive(cbusy_percentAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_utilization_count_get function as declared in rocm_smi/rocm_smi.h:2543
func rsmi_utilization_count_get(dv_ind uint32, utilization_counters *rsmi_utilization_counter, count uint32, timestamp *uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cutilization_counters, cutilization_countersAllocMap := utilization_counters.PassRef()
	ccount, ccountAllocMap := (C.uint32_t)(count), cgoAllocsUnknown
	ctimestamp, ctimestampAllocMap := (*C.uint64_t)(unsafe.Pointer(timestamp)), cgoAllocsUnknown
	__ret := C.rsmi_utilization_count_get(cdv_ind, cutilization_counters, ccount, ctimestamp)
	runtime.KeepAlive(ctimestampAllocMap)
	runtime.KeepAlive(ccountAllocMap)
	runtime.KeepAlive(cutilization_countersAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_activity_metric_get function as declared in rocm_smi/rocm_smi.h:2572
func rsmi_dev_activity_metric_get(dv_ind uint32, activity_metric_type rsmi_activity_metric, activity_metric_counter *rsmi_activity_metric_counter) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cactivity_metric_type, cactivity_metric_typeAllocMap := (C.rsmi_activity_metric_t)(activity_metric_type), cgoAllocsUnknown
	cactivity_metric_counter, cactivity_metric_counterAllocMap := activity_metric_counter.PassRef()
	__ret := C.rsmi_dev_activity_metric_get(cdv_ind, cactivity_metric_type, cactivity_metric_counter)
	runtime.KeepAlive(cactivity_metric_counterAllocMap)
	runtime.KeepAlive(cactivity_metric_typeAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_activity_avg_mm_get function as declared in rocm_smi/rocm_smi.h:2597
func rsmi_dev_activity_avg_mm_get(dv_ind uint32, avg_activity *uint16) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cavg_activity, cavg_activityAllocMap := (*C.uint16_t)(unsafe.Pointer(avg_activity)), cgoAllocsUnknown
	__ret := C.rsmi_dev_activity_avg_mm_get(cdv_ind, cavg_activity)
	runtime.KeepAlive(cavg_activityAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_perf_level_get function as declared in rocm_smi/rocm_smi.h:2622
func rsmi_dev_perf_level_get(dv_ind uint32, perf *rsmi_dev_perf_level) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cperf, cperfAllocMap := (*C.rsmi_dev_perf_level_t)(unsafe.Pointer(perf)), cgoAllocsUnknown
	__ret := C.rsmi_dev_perf_level_get(cdv_ind, cperf)
	runtime.KeepAlive(cperfAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_perf_determinism_mode_set function as declared in rocm_smi/rocm_smi.h:2646
func rsmi_perf_determinism_mode_set(dv_ind uint32, clkvalue uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cclkvalue, cclkvalueAllocMap := (C.uint64_t)(clkvalue), cgoAllocsUnknown
	__ret := C.rsmi_perf_determinism_mode_set(cdv_ind, cclkvalue)
	runtime.KeepAlive(cclkvalueAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_overdrive_level_get function as declared in rocm_smi/rocm_smi.h:2672
func rsmi_dev_overdrive_level_get(dv_ind uint32, od *uint32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cod, codAllocMap := (*C.uint32_t)(unsafe.Pointer(od)), cgoAllocsUnknown
	__ret := C.rsmi_dev_overdrive_level_get(cdv_ind, cod)
	runtime.KeepAlive(codAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_mem_overdrive_level_get function as declared in rocm_smi/rocm_smi.h:2697
func rsmi_dev_mem_overdrive_level_get(dv_ind uint32, od *uint32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cod, codAllocMap := (*C.uint32_t)(unsafe.Pointer(od)), cgoAllocsUnknown
	__ret := C.rsmi_dev_mem_overdrive_level_get(cdv_ind, cod)
	runtime.KeepAlive(codAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_gpu_clk_freq_get function as declared in rocm_smi/rocm_smi.h:2731
func rsmi_dev_gpu_clk_freq_get(dv_ind uint32, clk_type rsmi_clk_type, f *rsmi_frequencies) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cclk_type, cclk_typeAllocMap := (C.rsmi_clk_type_t)(clk_type), cgoAllocsUnknown
	cf, cfAllocMap := f.PassRef()
	__ret := C.rsmi_dev_gpu_clk_freq_get(cdv_ind, cclk_type, cf)
	runtime.KeepAlive(cfAllocMap)
	runtime.KeepAlive(cclk_typeAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_gpu_reset function as declared in rocm_smi/rocm_smi.h:2747
func rsmi_dev_gpu_reset(dv_ind uint32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	__ret := C.rsmi_dev_gpu_reset(cdv_ind)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_od_volt_info_get function as declared in rocm_smi/rocm_smi.h:2769
func rsmi_dev_od_volt_info_get(dv_ind uint32, odv *rsmi_od_volt_freq_data) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	codv, codvAllocMap := odv.PassRef()
	__ret := C.rsmi_dev_od_volt_info_get(cdv_ind, codv)
	runtime.KeepAlive(codvAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_gpu_metrics_info_get function as declared in rocm_smi/rocm_smi.h:2792
func rsmi_dev_gpu_metrics_info_get(dv_ind uint32, pgpu_metrics *rsmi_gpu_metrics) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cpgpu_metrics, cpgpu_metricsAllocMap := pgpu_metrics.PassRef()
	__ret := C.rsmi_dev_gpu_metrics_info_get(cdv_ind, cpgpu_metrics)
	runtime.KeepAlive(cpgpu_metricsAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_clk_range_set function as declared in rocm_smi/rocm_smi.h:2817
func rsmi_dev_clk_range_set(dv_ind uint32, minclkvalue uint64, maxclkvalue uint64, clkType rsmi_clk_type) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cminclkvalue, cminclkvalueAllocMap := (C.uint64_t)(minclkvalue), cgoAllocsUnknown
	cmaxclkvalue, cmaxclkvalueAllocMap := (C.uint64_t)(maxclkvalue), cgoAllocsUnknown
	cclkType, cclkTypeAllocMap := (C.rsmi_clk_type_t)(clkType), cgoAllocsUnknown
	__ret := C.rsmi_dev_clk_range_set(cdv_ind, cminclkvalue, cmaxclkvalue, cclkType)
	runtime.KeepAlive(cclkTypeAllocMap)
	runtime.KeepAlive(cmaxclkvalueAllocMap)
	runtime.KeepAlive(cminclkvalueAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_clk_extremum_set function as declared in rocm_smi/rocm_smi.h:2842
func rsmi_dev_clk_extremum_set(dv_ind uint32, level rsmi_freq_ind, clkvalue uint64, clkType rsmi_clk_type) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	clevel, clevelAllocMap := (C.rsmi_freq_ind_t)(level), cgoAllocsUnknown
	cclkvalue, cclkvalueAllocMap := (C.uint64_t)(clkvalue), cgoAllocsUnknown
	cclkType, cclkTypeAllocMap := (C.rsmi_clk_type_t)(clkType), cgoAllocsUnknown
	__ret := C.rsmi_dev_clk_extremum_set(cdv_ind, clevel, cclkvalue, cclkType)
	runtime.KeepAlive(cclkTypeAllocMap)
	runtime.KeepAlive(cclkvalueAllocMap)
	runtime.KeepAlive(clevelAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_od_clk_info_set function as declared in rocm_smi/rocm_smi.h:2868
func rsmi_dev_od_clk_info_set(dv_ind uint32, level rsmi_freq_ind, clkvalue uint64, clkType rsmi_clk_type) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	clevel, clevelAllocMap := (C.rsmi_freq_ind_t)(level), cgoAllocsUnknown
	cclkvalue, cclkvalueAllocMap := (C.uint64_t)(clkvalue), cgoAllocsUnknown
	cclkType, cclkTypeAllocMap := (C.rsmi_clk_type_t)(clkType), cgoAllocsUnknown
	__ret := C.rsmi_dev_od_clk_info_set(cdv_ind, clevel, cclkvalue, cclkType)
	runtime.KeepAlive(cclkTypeAllocMap)
	runtime.KeepAlive(cclkvalueAllocMap)
	runtime.KeepAlive(clevelAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_od_volt_info_set function as declared in rocm_smi/rocm_smi.h:2893
func rsmi_dev_od_volt_info_set(dv_ind uint32, vpoint uint32, clkvalue uint64, voltvalue uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cvpoint, cvpointAllocMap := (C.uint32_t)(vpoint), cgoAllocsUnknown
	cclkvalue, cclkvalueAllocMap := (C.uint64_t)(clkvalue), cgoAllocsUnknown
	cvoltvalue, cvoltvalueAllocMap := (C.uint64_t)(voltvalue), cgoAllocsUnknown
	__ret := C.rsmi_dev_od_volt_info_set(cdv_ind, cvpoint, cclkvalue, cvoltvalue)
	runtime.KeepAlive(cvoltvalueAllocMap)
	runtime.KeepAlive(cclkvalueAllocMap)
	runtime.KeepAlive(cvpointAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_od_volt_curve_regions_get function as declared in rocm_smi/rocm_smi.h:2934
func rsmi_dev_od_volt_curve_regions_get(dv_ind uint32, num_regions *uint32, buffer *rsmi_freq_volt_region) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cnum_regions, cnum_regionsAllocMap := (*C.uint32_t)(unsafe.Pointer(num_regions)), cgoAllocsUnknown
	cbuffer, cbufferAllocMap := buffer.PassRef()
	__ret := C.rsmi_dev_od_volt_curve_regions_get(cdv_ind, cnum_regions, cbuffer)
	runtime.KeepAlive(cbufferAllocMap)
	runtime.KeepAlive(cnum_regionsAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_power_profile_presets_get function as declared in rocm_smi/rocm_smi.h:2973
func rsmi_dev_power_profile_presets_get(dv_ind uint32, sensor_ind uint32, status *rsmi_power_profile_status) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	csensor_ind, csensor_indAllocMap := (C.uint32_t)(sensor_ind), cgoAllocsUnknown
	cstatus, cstatusAllocMap := status.PassRef()
	__ret := C.rsmi_dev_power_profile_presets_get(cdv_ind, csensor_ind, cstatus)
	runtime.KeepAlive(cstatusAllocMap)
	runtime.KeepAlive(csensor_indAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_perf_level_set function as declared in rocm_smi/rocm_smi.h:3006
func rsmi_dev_perf_level_set(dv_ind uint32, perf_lvl rsmi_dev_perf_level) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cperf_lvl, cperf_lvlAllocMap := (C.rsmi_dev_perf_level_t)(perf_lvl), cgoAllocsUnknown
	__ret := C.rsmi_dev_perf_level_set(cdv_ind, cperf_lvl)
	runtime.KeepAlive(cperf_lvlAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_perf_level_set_v1 function as declared in rocm_smi/rocm_smi.h:3027
func rsmi_dev_perf_level_set_v1(dv_ind uint32, perf_lvl rsmi_dev_perf_level) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cperf_lvl, cperf_lvlAllocMap := (C.rsmi_dev_perf_level_t)(perf_lvl), cgoAllocsUnknown
	__ret := C.rsmi_dev_perf_level_set_v1(cdv_ind, cperf_lvl)
	runtime.KeepAlive(cperf_lvlAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_overdrive_level_set function as declared in rocm_smi/rocm_smi.h:3072
func rsmi_dev_overdrive_level_set(dv_ind uint32, od uint32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cod, codAllocMap := (C.uint32_t)(od), cgoAllocsUnknown
	__ret := C.rsmi_dev_overdrive_level_set(cdv_ind, cod)
	runtime.KeepAlive(codAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_overdrive_level_set_v1 function as declared in rocm_smi/rocm_smi.h:3113
func rsmi_dev_overdrive_level_set_v1(dv_ind uint32, od uint32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cod, codAllocMap := (C.uint32_t)(od), cgoAllocsUnknown
	__ret := C.rsmi_dev_overdrive_level_set_v1(cdv_ind, cod)
	runtime.KeepAlive(codAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_gpu_clk_freq_set function as declared in rocm_smi/rocm_smi.h:3149
func rsmi_dev_gpu_clk_freq_set(dv_ind uint32, clk_type rsmi_clk_type, freq_bitmask uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cclk_type, cclk_typeAllocMap := (C.rsmi_clk_type_t)(clk_type), cgoAllocsUnknown
	cfreq_bitmask, cfreq_bitmaskAllocMap := (C.uint64_t)(freq_bitmask), cgoAllocsUnknown
	__ret := C.rsmi_dev_gpu_clk_freq_set(cdv_ind, cclk_type, cfreq_bitmask)
	runtime.KeepAlive(cfreq_bitmaskAllocMap)
	runtime.KeepAlive(cclk_typeAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_version_get function as declared in rocm_smi/rocm_smi.h:3174
func rsmi_version_get(version *rsmi_version) rsmi_status {
	cversion, cversionAllocMap := version.PassRef()
	__ret := C.rsmi_version_get(cversion)
	runtime.KeepAlive(cversionAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_version_str_get function as declared in rocm_smi/rocm_smi.h:3202
func rsmi_version_str_get(component rsmi_sw_component, ver_str *byte, len uint32) rsmi_status {
	ccomponent, ccomponentAllocMap := (C.rsmi_sw_component_t)(component), cgoAllocsUnknown
	cver_str, cver_strAllocMap := (*C.char)(unsafe.Pointer(ver_str)), cgoAllocsUnknown
	clen, clenAllocMap := (C.uint32_t)(len), cgoAllocsUnknown
	__ret := C.rsmi_version_str_get(ccomponent, cver_str, clen)
	runtime.KeepAlive(clenAllocMap)
	runtime.KeepAlive(cver_strAllocMap)
	runtime.KeepAlive(ccomponentAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_vbios_version_get function as declared in rocm_smi/rocm_smi.h:3232
func rsmi_dev_vbios_version_get(dv_ind uint32, vbios *byte, len uint32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cvbios, cvbiosAllocMap := (*C.char)(unsafe.Pointer(vbios)), cgoAllocsUnknown
	clen, clenAllocMap := (C.uint32_t)(len), cgoAllocsUnknown
	__ret := C.rsmi_dev_vbios_version_get(cdv_ind, cvbios, clen)
	runtime.KeepAlive(clenAllocMap)
	runtime.KeepAlive(cvbiosAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_firmware_version_get function as declared in rocm_smi/rocm_smi.h:3259
func rsmi_dev_firmware_version_get(dv_ind uint32, block rsmi_fw_block, fw_version *uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cblock, cblockAllocMap := (C.rsmi_fw_block_t)(block), cgoAllocsUnknown
	cfw_version, cfw_versionAllocMap := (*C.uint64_t)(unsafe.Pointer(fw_version)), cgoAllocsUnknown
	__ret := C.rsmi_dev_firmware_version_get(cdv_ind, cblock, cfw_version)
	runtime.KeepAlive(cfw_versionAllocMap)
	runtime.KeepAlive(cblockAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_target_graphics_version_get function as declared in rocm_smi/rocm_smi.h:3282
func rsmi_dev_target_graphics_version_get(dv_ind uint32, gfx_version *uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cgfx_version, cgfx_versionAllocMap := (*C.uint64_t)(unsafe.Pointer(gfx_version)), cgoAllocsUnknown
	__ret := C.rsmi_dev_target_graphics_version_get(cdv_ind, cgfx_version)
	runtime.KeepAlive(cgfx_versionAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_ecc_count_get function as declared in rocm_smi/rocm_smi.h:3319
func rsmi_dev_ecc_count_get(dv_ind uint32, block rsmi_gpu_block, ec *rsmi_error_count) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cblock, cblockAllocMap := (C.rsmi_gpu_block_t)(block), cgoAllocsUnknown
	cec, cecAllocMap := ec.PassRef()
	__ret := C.rsmi_dev_ecc_count_get(cdv_ind, cblock, cec)
	runtime.KeepAlive(cecAllocMap)
	runtime.KeepAlive(cblockAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_ecc_enabled_get function as declared in rocm_smi/rocm_smi.h:3349
func rsmi_dev_ecc_enabled_get(dv_ind uint32, enabled_blocks *uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cenabled_blocks, cenabled_blocksAllocMap := (*C.uint64_t)(unsafe.Pointer(enabled_blocks)), cgoAllocsUnknown
	__ret := C.rsmi_dev_ecc_enabled_get(cdv_ind, cenabled_blocks)
	runtime.KeepAlive(cenabled_blocksAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_ecc_status_get function as declared in rocm_smi/rocm_smi.h:3377
func rsmi_dev_ecc_status_get(dv_ind uint32, block rsmi_gpu_block, state *rsmi_ras_err_state) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cblock, cblockAllocMap := (C.rsmi_gpu_block_t)(block), cgoAllocsUnknown
	cstate, cstateAllocMap := (*C.rsmi_ras_err_state_t)(unsafe.Pointer(state)), cgoAllocsUnknown
	__ret := C.rsmi_dev_ecc_status_get(cdv_ind, cblock, cstate)
	runtime.KeepAlive(cstateAllocMap)
	runtime.KeepAlive(cblockAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_status_string function as declared in rocm_smi/rocm_smi.h:3394
func rsmi_status_string(status rsmi_status, status_string []string) rsmi_status {
	cstatus, cstatusAllocMap := (C.rsmi_status_t)(status), cgoAllocsUnknown
	cstatus_string, cstatus_stringAllocMap := unpackArgSString(status_string)
	__ret := C.rsmi_status_string(cstatus, cstatus_string)
	packSString(status_string, cstatus_string)
	runtime.KeepAlive(cstatus_stringAllocMap)
	runtime.KeepAlive(cstatusAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_counter_group_supported function as declared in rocm_smi/rocm_smi.h:3520
func rsmi_dev_counter_group_supported(dv_ind uint32, group rsmi_event_group) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cgroup, cgroupAllocMap := (C.rsmi_event_group_t)(group), cgoAllocsUnknown
	__ret := C.rsmi_dev_counter_group_supported(cdv_ind, cgroup)
	runtime.KeepAlive(cgroupAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_counter_create function as declared in rocm_smi/rocm_smi.h:3551
func rsmi_dev_counter_create(dv_ind uint32, _type rsmi_event_type, evnt_handle *rsmi_event_handle) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	c_type, c_typeAllocMap := (C.rsmi_event_type_t)(_type), cgoAllocsUnknown
	cevnt_handle, cevnt_handleAllocMap := (*C.rsmi_event_handle_t)(unsafe.Pointer(evnt_handle)), cgoAllocsUnknown
	__ret := C.rsmi_dev_counter_create(cdv_ind, c_type, cevnt_handle)
	runtime.KeepAlive(cevnt_handleAllocMap)
	runtime.KeepAlive(c_typeAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_counter_destroy function as declared in rocm_smi/rocm_smi.h:3568
func rsmi_dev_counter_destroy(evnt_handle rsmi_event_handle) rsmi_status {
	cevnt_handle, cevnt_handleAllocMap := (C.rsmi_event_handle_t)(evnt_handle), cgoAllocsUnknown
	__ret := C.rsmi_dev_counter_destroy(cevnt_handle)
	runtime.KeepAlive(cevnt_handleAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_counter_control function as declared in rocm_smi/rocm_smi.h:3588
func rsmi_counter_control(evt_handle rsmi_event_handle, cmd rsmi_counter_command, cmd_args unsafe.Pointer) rsmi_status {
	cevt_handle, cevt_handleAllocMap := (C.rsmi_event_handle_t)(evt_handle), cgoAllocsUnknown
	ccmd, ccmdAllocMap := (C.rsmi_counter_command_t)(cmd), cgoAllocsUnknown
	ccmd_args, ccmd_argsAllocMap := cmd_args, cgoAllocsUnknown
	__ret := C.rsmi_counter_control(cevt_handle, ccmd, ccmd_args)
	runtime.KeepAlive(ccmd_argsAllocMap)
	runtime.KeepAlive(ccmdAllocMap)
	runtime.KeepAlive(cevt_handleAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_counter_read function as declared in rocm_smi/rocm_smi.h:3609
func rsmi_counter_read(evt_handle rsmi_event_handle, value *rsmi_counter_value) rsmi_status {
	cevt_handle, cevt_handleAllocMap := (C.rsmi_event_handle_t)(evt_handle), cgoAllocsUnknown
	cvalue, cvalueAllocMap := value.PassRef()
	__ret := C.rsmi_counter_read(cevt_handle, cvalue)
	runtime.KeepAlive(cvalueAllocMap)
	runtime.KeepAlive(cevt_handleAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_counter_available_counters_get function as declared in rocm_smi/rocm_smi.h:3632
func rsmi_counter_available_counters_get(dv_ind uint32, grp rsmi_event_group, available *uint32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cgrp, cgrpAllocMap := (C.rsmi_event_group_t)(grp), cgoAllocsUnknown
	cavailable, cavailableAllocMap := (*C.uint32_t)(unsafe.Pointer(available)), cgoAllocsUnknown
	__ret := C.rsmi_counter_available_counters_get(cdv_ind, cgrp, cavailable)
	runtime.KeepAlive(cavailableAllocMap)
	runtime.KeepAlive(cgrpAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_compute_process_info_get function as declared in rocm_smi/rocm_smi.h:3675
func rsmi_compute_process_info_get(procs *rsmi_process_info, num_items *uint32) rsmi_status {
	cprocs, cprocsAllocMap := procs.PassRef()
	cnum_items, cnum_itemsAllocMap := (*C.uint32_t)(unsafe.Pointer(num_items)), cgoAllocsUnknown
	__ret := C.rsmi_compute_process_info_get(cprocs, cnum_items)
	runtime.KeepAlive(cnum_itemsAllocMap)
	runtime.KeepAlive(cprocsAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_compute_process_info_by_pid_get function as declared in rocm_smi/rocm_smi.h:3699
func rsmi_compute_process_info_by_pid_get(pid uint32, proc *rsmi_process_info) rsmi_status {
	cpid, cpidAllocMap := (C.uint32_t)(pid), cgoAllocsUnknown
	cproc, cprocAllocMap := proc.PassRef()
	__ret := C.rsmi_compute_process_info_by_pid_get(cpid, cproc)
	runtime.KeepAlive(cprocAllocMap)
	runtime.KeepAlive(cpidAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_compute_process_gpus_get function as declared in rocm_smi/rocm_smi.h:3736
func rsmi_compute_process_gpus_get(pid uint32, dv_indices *uint32, num_devices *uint32) rsmi_status {
	cpid, cpidAllocMap := (C.uint32_t)(pid), cgoAllocsUnknown
	cdv_indices, cdv_indicesAllocMap := (*C.uint32_t)(unsafe.Pointer(dv_indices)), cgoAllocsUnknown
	cnum_devices, cnum_devicesAllocMap := (*C.uint32_t)(unsafe.Pointer(num_devices)), cgoAllocsUnknown
	__ret := C.rsmi_compute_process_gpus_get(cpid, cdv_indices, cnum_devices)
	runtime.KeepAlive(cnum_devicesAllocMap)
	runtime.KeepAlive(cdv_indicesAllocMap)
	runtime.KeepAlive(cpidAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_compute_process_info_by_device_get function as declared in rocm_smi/rocm_smi.h:3759
func rsmi_compute_process_info_by_device_get(pid uint32, dv_ind uint32, proc *rsmi_process_info) rsmi_status {
	cpid, cpidAllocMap := (C.uint32_t)(pid), cgoAllocsUnknown
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cproc, cprocAllocMap := proc.PassRef()
	__ret := C.rsmi_compute_process_info_by_device_get(cpid, cdv_ind, cproc)
	runtime.KeepAlive(cprocAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	runtime.KeepAlive(cpidAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_xgmi_error_status function as declared in rocm_smi/rocm_smi.h:3794
func rsmi_dev_xgmi_error_status(dv_ind uint32, status *rsmi_xgmi_status) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cstatus, cstatusAllocMap := (*C.rsmi_xgmi_status_t)(unsafe.Pointer(status)), cgoAllocsUnknown
	__ret := C.rsmi_dev_xgmi_error_status(cdv_ind, cstatus)
	runtime.KeepAlive(cstatusAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_xgmi_error_reset function as declared in rocm_smi/rocm_smi.h:3809
func rsmi_dev_xgmi_error_reset(dv_ind uint32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	__ret := C.rsmi_dev_xgmi_error_reset(cdv_ind)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_xgmi_hive_id_get function as declared in rocm_smi/rocm_smi.h:3830
func rsmi_dev_xgmi_hive_id_get(dv_ind uint32, hive_id *uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	chive_id, chive_idAllocMap := (*C.uint64_t)(unsafe.Pointer(hive_id)), cgoAllocsUnknown
	__ret := C.rsmi_dev_xgmi_hive_id_get(cdv_ind, chive_id)
	runtime.KeepAlive(chive_idAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_topo_get_numa_node_number function as declared in rocm_smi/rocm_smi.h:3858
func rsmi_topo_get_numa_node_number(dv_ind uint32, numa_node *uint32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cnuma_node, cnuma_nodeAllocMap := (*C.uint32_t)(unsafe.Pointer(numa_node)), cgoAllocsUnknown
	__ret := C.rsmi_topo_get_numa_node_number(cdv_ind, cnuma_node)
	runtime.KeepAlive(cnuma_nodeAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_topo_get_link_weight function as declared in rocm_smi/rocm_smi.h:3881
func rsmi_topo_get_link_weight(dv_ind_src uint32, dv_ind_dst uint32, weight *uint64) rsmi_status {
	cdv_ind_src, cdv_ind_srcAllocMap := (C.uint32_t)(dv_ind_src), cgoAllocsUnknown
	cdv_ind_dst, cdv_ind_dstAllocMap := (C.uint32_t)(dv_ind_dst), cgoAllocsUnknown
	cweight, cweightAllocMap := (*C.uint64_t)(unsafe.Pointer(weight)), cgoAllocsUnknown
	__ret := C.rsmi_topo_get_link_weight(cdv_ind_src, cdv_ind_dst, cweight)
	runtime.KeepAlive(cweightAllocMap)
	runtime.KeepAlive(cdv_ind_dstAllocMap)
	runtime.KeepAlive(cdv_ind_srcAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_minmax_bandwidth_get function as declared in rocm_smi/rocm_smi.h:3907
func rsmi_minmax_bandwidth_get(dv_ind_src uint32, dv_ind_dst uint32, min_bandwidth *uint64, max_bandwidth *uint64) rsmi_status {
	cdv_ind_src, cdv_ind_srcAllocMap := (C.uint32_t)(dv_ind_src), cgoAllocsUnknown
	cdv_ind_dst, cdv_ind_dstAllocMap := (C.uint32_t)(dv_ind_dst), cgoAllocsUnknown
	cmin_bandwidth, cmin_bandwidthAllocMap := (*C.uint64_t)(unsafe.Pointer(min_bandwidth)), cgoAllocsUnknown
	cmax_bandwidth, cmax_bandwidthAllocMap := (*C.uint64_t)(unsafe.Pointer(max_bandwidth)), cgoAllocsUnknown
	__ret := C.rsmi_minmax_bandwidth_get(cdv_ind_src, cdv_ind_dst, cmin_bandwidth, cmax_bandwidth)
	runtime.KeepAlive(cmax_bandwidthAllocMap)
	runtime.KeepAlive(cmin_bandwidthAllocMap)
	runtime.KeepAlive(cdv_ind_dstAllocMap)
	runtime.KeepAlive(cdv_ind_srcAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_topo_get_link_type function as declared in rocm_smi/rocm_smi.h:3943
func rsmi_topo_get_link_type(dv_ind_src uint32, dv_ind_dst uint32, hops *uint64, _type *RSMI_IO_LINK) rsmi_status {
	cdv_ind_src, cdv_ind_srcAllocMap := (C.uint32_t)(dv_ind_src), cgoAllocsUnknown
	cdv_ind_dst, cdv_ind_dstAllocMap := (C.uint32_t)(dv_ind_dst), cgoAllocsUnknown
	chops, chopsAllocMap := (*C.uint64_t)(unsafe.Pointer(hops)), cgoAllocsUnknown
	c_type, c_typeAllocMap := (*C.RSMI_IO_LINK_TYPE)(unsafe.Pointer(_type)), cgoAllocsUnknown
	__ret := C.rsmi_topo_get_link_type(cdv_ind_src, cdv_ind_dst, chops, c_type)
	runtime.KeepAlive(c_typeAllocMap)
	runtime.KeepAlive(chopsAllocMap)
	runtime.KeepAlive(cdv_ind_dstAllocMap)
	runtime.KeepAlive(cdv_ind_srcAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_is_P2P_accessible function as declared in rocm_smi/rocm_smi.h:3967
func rsmi_is_P2P_accessible(dv_ind_src uint32, dv_ind_dst uint32, accessible *bool) rsmi_status {
	cdv_ind_src, cdv_ind_srcAllocMap := (C.uint32_t)(dv_ind_src), cgoAllocsUnknown
	cdv_ind_dst, cdv_ind_dstAllocMap := (C.uint32_t)(dv_ind_dst), cgoAllocsUnknown
	caccessible, caccessibleAllocMap := (*C._Bool)(unsafe.Pointer(accessible)), cgoAllocsUnknown
	__ret := C.rsmi_is_P2P_accessible(cdv_ind_src, cdv_ind_dst, caccessible)
	runtime.KeepAlive(caccessibleAllocMap)
	runtime.KeepAlive(cdv_ind_dstAllocMap)
	runtime.KeepAlive(cdv_ind_srcAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_compute_partition_get function as declared in rocm_smi/rocm_smi.h:4008
func rsmi_dev_compute_partition_get(dv_ind uint32, compute_partition *byte, len uint32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	ccompute_partition, ccompute_partitionAllocMap := (*C.char)(unsafe.Pointer(compute_partition)), cgoAllocsUnknown
	clen, clenAllocMap := (C.uint32_t)(len), cgoAllocsUnknown
	__ret := C.rsmi_dev_compute_partition_get(cdv_ind, ccompute_partition, clen)
	runtime.KeepAlive(clenAllocMap)
	runtime.KeepAlive(ccompute_partitionAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_compute_partition_set function as declared in rocm_smi/rocm_smi.h:4036
func rsmi_dev_compute_partition_set(dv_ind uint32, compute_partition rsmi_compute_partition_type) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	ccompute_partition, ccompute_partitionAllocMap := (C.rsmi_compute_partition_type_t)(compute_partition), cgoAllocsUnknown
	__ret := C.rsmi_dev_compute_partition_set(cdv_ind, ccompute_partition)
	runtime.KeepAlive(ccompute_partitionAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_compute_partition_reset function as declared in rocm_smi/rocm_smi.h:4056
func rsmi_dev_compute_partition_reset(dv_ind uint32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	__ret := C.rsmi_dev_compute_partition_reset(cdv_ind)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_memory_partition_get function as declared in rocm_smi/rocm_smi.h:4096
func rsmi_dev_memory_partition_get(dv_ind uint32, memory_partition *byte, len uint32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cmemory_partition, cmemory_partitionAllocMap := (*C.char)(unsafe.Pointer(memory_partition)), cgoAllocsUnknown
	clen, clenAllocMap := (C.uint32_t)(len), cgoAllocsUnknown
	__ret := C.rsmi_dev_memory_partition_get(cdv_ind, cmemory_partition, clen)
	runtime.KeepAlive(clenAllocMap)
	runtime.KeepAlive(cmemory_partitionAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_memory_partition_set function as declared in rocm_smi/rocm_smi.h:4123
func rsmi_dev_memory_partition_set(dv_ind uint32, memory_partition rsmi_memory_partition_type) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cmemory_partition, cmemory_partitionAllocMap := (C.rsmi_memory_partition_type_t)(memory_partition), cgoAllocsUnknown
	__ret := C.rsmi_dev_memory_partition_set(cdv_ind, cmemory_partition)
	runtime.KeepAlive(cmemory_partitionAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_memory_partition_reset function as declared in rocm_smi/rocm_smi.h:4145
func rsmi_dev_memory_partition_reset(dv_ind uint32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	__ret := C.rsmi_dev_memory_partition_reset(cdv_ind)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_supported_func_iterator_open function as declared in rocm_smi/rocm_smi.h:4283
func rsmi_dev_supported_func_iterator_open(dv_ind uint32, handle *rsmi_func_id_iter_handle) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	chandle, chandleAllocMap := handle.PassRef()
	__ret := C.rsmi_dev_supported_func_iterator_open(cdv_ind, chandle)
	runtime.KeepAlive(chandleAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_supported_variant_iterator_open function as declared in rocm_smi/rocm_smi.h:4311
func rsmi_dev_supported_variant_iterator_open(obj_h rsmi_func_id_iter_handle, var_iter *rsmi_func_id_iter_handle) rsmi_status {
	cobj_h, cobj_hAllocMap := obj_h.PassValue()
	cvar_iter, cvar_iterAllocMap := var_iter.PassRef()
	__ret := C.rsmi_dev_supported_variant_iterator_open(cobj_h, cvar_iter)
	runtime.KeepAlive(cvar_iterAllocMap)
	runtime.KeepAlive(cobj_hAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_func_iter_next function as declared in rocm_smi/rocm_smi.h:4333
func rsmi_func_iter_next(handle rsmi_func_id_iter_handle) rsmi_status {
	chandle, chandleAllocMap := handle.PassValue()
	__ret := C.rsmi_func_iter_next(chandle)
	runtime.KeepAlive(chandleAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_supported_func_iterator_close function as declared in rocm_smi/rocm_smi.h:4347
func rsmi_dev_supported_func_iterator_close(handle *rsmi_func_id_iter_handle) rsmi_status {
	chandle, chandleAllocMap := handle.PassRef()
	__ret := C.rsmi_dev_supported_func_iterator_close(chandle)
	runtime.KeepAlive(chandleAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_func_iter_value_get function as declared in rocm_smi/rocm_smi.h:4368
func rsmi_func_iter_value_get(handle rsmi_func_id_iter_handle, value *rsmi_func_id_value) rsmi_status {
	chandle, chandleAllocMap := handle.PassValue()
	cvalue, cvalueAllocMap := (*C.rsmi_func_id_value_t)(unsafe.Pointer(value)), cgoAllocsUnknown
	__ret := C.rsmi_func_iter_value_get(chandle, cvalue)
	runtime.KeepAlive(cvalueAllocMap)
	runtime.KeepAlive(chandleAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_event_notification_init function as declared in rocm_smi/rocm_smi.h:4394
func rsmi_event_notification_init(dv_ind uint32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	__ret := C.rsmi_event_notification_init(cdv_ind)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_event_notification_mask_set function as declared in rocm_smi/rocm_smi.h:4423
func rsmi_event_notification_mask_set(dv_ind uint32, mask uint64) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cmask, cmaskAllocMap := (C.uint64_t)(mask), cgoAllocsUnknown
	__ret := C.rsmi_event_notification_mask_set(cdv_ind, cmask)
	runtime.KeepAlive(cmaskAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_event_notification_get function as declared in rocm_smi/rocm_smi.h:4466
func rsmi_event_notification_get(timeout_ms int32, num_elem *uint32, data *rsmi_evt_notification_data) rsmi_status {
	ctimeout_ms, ctimeout_msAllocMap := (C.int)(timeout_ms), cgoAllocsUnknown
	cnum_elem, cnum_elemAllocMap := (*C.uint32_t)(unsafe.Pointer(num_elem)), cgoAllocsUnknown
	cdata, cdataAllocMap := data.PassRef()
	__ret := C.rsmi_event_notification_get(ctimeout_ms, cnum_elem, cdata)
	runtime.KeepAlive(cdataAllocMap)
	runtime.KeepAlive(cnum_elemAllocMap)
	runtime.KeepAlive(ctimeout_msAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_event_notification_stop function as declared in rocm_smi/rocm_smi.h:4487
func rsmi_event_notification_stop(dv_ind uint32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	__ret := C.rsmi_event_notification_stop(cdv_ind)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_metrics_header_info_get function as declared in rocm_smi/rocm_smi.h:4516
func rsmi_dev_metrics_header_info_get(dv_ind uint32, header_value *metrics_table_header) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cheader_value, cheader_valueAllocMap := header_value.PassRef()
	__ret := C.rsmi_dev_metrics_header_info_get(cdv_ind, cheader_value)
	runtime.KeepAlive(cheader_valueAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_metrics_xcd_counter_get function as declared in rocm_smi/rocm_smi.h:4535
func rsmi_dev_metrics_xcd_counter_get(dv_ind uint32, xcd_counter_value *uint16) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	cxcd_counter_value, cxcd_counter_valueAllocMap := (*C.uint16_t)(unsafe.Pointer(xcd_counter_value)), cgoAllocsUnknown
	__ret := C.rsmi_dev_metrics_xcd_counter_get(cdv_ind, cxcd_counter_value)
	runtime.KeepAlive(cxcd_counter_valueAllocMap)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}

// rsmi_dev_metrics_log_get function as declared in rocm_smi/rocm_smi.h:4549
func rsmi_dev_metrics_log_get(dv_ind uint32) rsmi_status {
	cdv_ind, cdv_indAllocMap := (C.uint32_t)(dv_ind), cgoAllocsUnknown
	__ret := C.rsmi_dev_metrics_log_get(cdv_ind)
	runtime.KeepAlive(cdv_indAllocMap)
	__v := (rsmi_status)(__ret)
	return __v
}
