// WARNING: This file has automatically been generated on Wed, 22 May 2024 00:28:34 KST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package rsmi

/*
#cgo linux LDFLAGS: -Wl,--export-dynamic -Wl,--unresolved-symbols=ignore-in-object-files
#include "rocm_smi/rocm_smi.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// rsmi_event_handle type as declared in rocm_smi/rocm_smi.h:207
type rsmi_event_handle uint64

// rsmi_counter_value as declared in rocm_smi/rocm_smi.h:308
type rsmi_counter_value struct {
	value          uint64
	time_enabled   uint64
	time_running   uint64
	ref3d716451    *C.rsmi_counter_value_t
	allocs3d716451 interface{}
}

// rsmi_evt_notification_data as declared in rocm_smi/rocm_smi.h:340
type rsmi_evt_notification_data struct {
	dv_ind         uint32
	event          rsmi_evt_notification_type
	message        [64]byte
	ref12bb4c74    *C.rsmi_evt_notification_data_t
	allocs12bb4c74 interface{}
}

// rsmi_bit_field type as declared in rocm_smi/rocm_smi.h:665
type rsmi_bit_field uint64

// rsmi_utilization_counter as declared in rocm_smi/rocm_smi.h:723
type rsmi_utilization_counter struct {
	_type          RSMI_UTILIZATION_COUNTER
	value          uint64
	refe35e64e9    *C.rsmi_utilization_counter_t
	allocse35e64e9 interface{}
}

// rsmi_retired_page_record as declared in rocm_smi/rocm_smi.h:732
type rsmi_retired_page_record struct {
	page_address   uint64
	page_size      uint64
	status         rsmi_memory_page_status
	ref5cd74c7e    *C.rsmi_retired_page_record_t
	allocs5cd74c7e interface{}
}

// rsmi_power_profile_status as declared in rocm_smi/rocm_smi.h:759
type rsmi_power_profile_status struct {
	available_profiles rsmi_bit_field
	current            rsmi_power_profile_preset_masks
	num_profiles       uint32
	refead6fdb         *C.rsmi_power_profile_status_t
	allocsead6fdb      interface{}
}

// rsmi_frequencies as declared in rocm_smi/rocm_smi.h:788
type rsmi_frequencies struct {
	has_deep_sleep bool
	num_supported  uint32
	current        uint32
	frequency      [33]uint64
	ref64cedbcf    *C.rsmi_frequencies_t
	allocs64cedbcf interface{}
}

// rsmi_pcie_bandwidth as declared in rocm_smi/rocm_smi.h:809
type rsmi_pcie_bandwidth struct {
	transfer_rate  rsmi_frequencies
	lanes          [33]uint32
	ref85c8716e    *C.rsmi_pcie_bandwidth_t
	allocs85c8716e interface{}
}

// rsmi_activity_metric_counter as declared in rocm_smi/rocm_smi.h:824
type rsmi_activity_metric_counter struct {
	average_gfx_activity uint16
	average_umc_activity uint16
	average_mm_activity  uint16
	ref12a9585f          *C.rsmi_activity_metric_counter_t
	allocs12a9585f       interface{}
}

// rsmi_version as declared in rocm_smi/rocm_smi.h:834
type rsmi_version struct {
	major          uint32
	minor          uint32
	patch          uint32
	build          string
	ref3a694ceb    *C.rsmi_version_t
	allocs3a694ceb interface{}
}

// rsmi_range as declared in rocm_smi/rocm_smi.h:844
type rsmi_range struct {
	lower_bound    uint64
	upper_bound    uint64
	ref904052bd    *C.rsmi_range_t
	allocs904052bd interface{}
}

// rsmi_od_vddc_point as declared in rocm_smi/rocm_smi.h:855
type rsmi_od_vddc_point struct {
	frequency      uint64
	voltage        uint64
	ref45c07bad    *C.rsmi_od_vddc_point_t
	allocs45c07bad interface{}
}

// rsmi_freq_volt_region as declared in rocm_smi/rocm_smi.h:868
type rsmi_freq_volt_region struct {
	freq_range     rsmi_range
	volt_range     rsmi_range
	ref2b8059c6    *C.rsmi_freq_volt_region_t
	allocs2b8059c6 interface{}
}

// rsmi_od_volt_curve as declared in rocm_smi/rocm_smi.h:882
type rsmi_od_volt_curve struct {
	vc_points      [3]rsmi_od_vddc_point
	refd69524af    *C.rsmi_od_volt_curve_t
	allocsd69524af interface{}
}

// rsmi_od_volt_freq_data as declared in rocm_smi/rocm_smi.h:902
type rsmi_od_volt_freq_data struct {
	curr_sclk_range  rsmi_range
	curr_mclk_range  rsmi_range
	sclk_freq_limits rsmi_range
	mclk_freq_limits rsmi_range
	curve            rsmi_od_volt_curve
	num_regions      uint32
	ref34ccd7b5      *C.rsmi_od_volt_freq_data_t
	allocs34ccd7b5   interface{}
}

// metrics_table_header as declared in rocm_smi/rocm_smi.h:925
type metrics_table_header struct {
	structure_size   uint16
	format_revision  byte
	content_revision byte
	ref81dc70c       *C.metrics_table_header_t
	allocs81dc70c    interface{}
}

// rsmi_gpu_metrics as declared in rocm_smi/rocm_smi.h:1119
type rsmi_gpu_metrics struct {
	common_header               metrics_table_header
	temperature_edge            uint16
	temperature_hotspot         uint16
	temperature_mem             uint16
	temperature_vrgfx           uint16
	temperature_vrsoc           uint16
	temperature_vrmem           uint16
	average_gfx_activity        uint16
	average_umc_activity        uint16
	average_mm_activity         uint16
	average_socket_power        uint16
	energy_accumulator          uint64
	system_clock_counter        uint64
	average_gfxclk_frequency    uint16
	average_socclk_frequency    uint16
	average_uclk_frequency      uint16
	average_vclk0_frequency     uint16
	average_dclk0_frequency     uint16
	average_vclk1_frequency     uint16
	average_dclk1_frequency     uint16
	current_gfxclk              uint16
	current_socclk              uint16
	current_uclk                uint16
	current_vclk0               uint16
	current_dclk0               uint16
	current_vclk1               uint16
	current_dclk1               uint16
	throttle_status             uint32
	current_fan_speed           uint16
	pcie_link_width             uint16
	pcie_link_speed             uint16
	gfx_activity_acc            uint32
	mem_activity_acc            uint32
	temperature_hbm             [4]uint16
	firmware_timestamp          uint64
	voltage_soc                 uint16
	voltage_gfx                 uint16
	voltage_mem                 uint16
	indep_throttle_status       uint64
	current_socket_power        uint16
	vcn_activity                [4]uint16
	gfxclk_lock_status          uint32
	xgmi_link_width             uint16
	xgmi_link_speed             uint16
	pcie_bandwidth_acc          uint64
	pcie_bandwidth_inst         uint64
	pcie_l0_to_recov_count_acc  uint64
	pcie_replay_count_acc       uint64
	pcie_replay_rover_count_acc uint64
	xgmi_read_data_acc          [8]uint64
	xgmi_write_data_acc         [8]uint64
	current_gfxclks             [8]uint16
	current_socclks             [4]uint16
	current_vclk0s              [4]uint16
	current_dclk0s              [4]uint16
	jpeg_activity               [32]uint16
	pcie_nak_sent_count_acc     uint32
	pcie_nak_rcvd_count_acc     uint32
	ref9356c676                 *C.rsmi_gpu_metrics_t
	allocs9356c676              interface{}
}

// rsmi_error_count as declared in rocm_smi/rocm_smi.h:1127
type rsmi_error_count struct {
	correctable_err   uint64
	uncorrectable_err uint64
	ref7689bfd2       *C.rsmi_error_count_t
	allocs7689bfd2    interface{}
}

// rsmi_process_info as declared in rocm_smi/rocm_smi.h:1138
type rsmi_process_info struct {
	process_id     uint32
	pasid          uint32
	vram_usage     uint64
	sdma_usage     uint64
	cu_occupancy   uint32
	ref3e0d7669    *C.rsmi_process_info_t
	allocs3e0d7669 interface{}
}

// rsmi_func_id_iter_handle as declared in rocm_smi/rocm_smi.h:1148
type rsmi_func_id_iter_handle struct {
	ref5ba822f7    *C.rsmi_func_id_iter_handle_t
	allocs5ba822f7 interface{}
}

// rsmi_func_id_value as declared in rocm_smi/rocm_smi.h:1178
const sizeofrsmi_func_id_value = unsafe.Sizeof(C.rsmi_func_id_value_t{})

type rsmi_func_id_value [sizeofrsmi_func_id_value]byte
